<script lang="ts">
  import Writeup from '../components/Writeup.svelte';
  import Item from '../components/Item.svelte';

  let baseImagePath = 'ConsCap/';
</script>

<Writeup>
  <Item>
    <div slot="left">
      Environmental harm
      <p>
        Capitalism causes massive harm to the environment, as corporations rush
        to take resources for themselves and use up things like fossil fuels
        unsustainably. In addition, mass consumption (a system that is
        encouraged under capitalism) worsens this issue, driving people to
        consume more to a point that is not sustainable.
      </p>
      <p>
        As the CDP has stated, “71% of all global GHG1 emissions since 1988 can
        be traced to just 100 fossil fuel producers”.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}garbage.png" alt="placeholder" srcset="" />
      <p class="description">
        (Pictured above is part of the great pacific garbage patch, a gigantic
        mass of waste in the ocean generated by overconsumption.)
      </p>
    </div>
  </Item>
  <Item>
    <div slot="left">
      Social harm
      <p>
        Capitalism as a system distributes wealth unevenly. As rich CEOs and
        corporate leaders reap the skewed benefit of everyone working under
        them, their workers are left to work, usually with poor conditions, for
        a wage that is not livable. While the majority of Americans are left
        with almost nothing, a small minority of Americans hoard most of the
        wealth for themselves.
      </p>
      <p>
        In addition, discriminatory factors like Race and Gender, Sexual
        orientation and religion can and usually do play into negative forces in
        captialism. For instance, women have and continue to be paid less
        working the exact same job that a man would be paid more for. This
        doesn’t even factor in race, which also plays a hand in the amount of
        money you make.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}table.png" alt="placeholder" srcset="" />
      <p class="description">
        (Pictured above is a cited image from Gilbert, Geoffrey. Rich and Poor
        in America : a Reference Handbook. This table shows wealth distribution
        in the US, showing how uneven wealth is distributed, with above 80% of
        the wealth going to the top fifth of Americans while the bottom four
        fifth are left with next to nothing.)
      </p>
    </div>
  </Item>
  <Item>
    <div slot="left">
      Economic Harm
      <p>
        The power of corporations given by a capitalist system allows large
        companies to control aspects of our everyday lives, which usually screws
        over the marginalized. For instance, the pharmaceutical industry
        controls the prices of drugs like insulin, which millions of Americans
        need to live. These products, due to the control of these industries,
        can become too costly for many people to buy, meaning many have to live
        in bad health, or outright die because they cannot afford these things.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}insulin.png" alt="insulin prices" />
      <p class="description">
        (Pictured above is a chart showcasing the average price of insulin in
        the US and comparable countries. This image showcases how badly skewed
        insulin is for the US as opposed to other nations.)
      </p>
    </div>
  </Item>
  <Item>
    <div slot="left">
      Political Harm
      <p>
        Corporations have the spending power to buy and control aspects of our
        government and undermine our democracy. This is enabled by things such
        as Citizens United vs. FEC, a supreme court case giving corporate
        interests no limits on political donations, which lets them lobby and
        advocate for decisions that go against the interests of everyday
        citizens
      </p>
      <p>
        In addition, these companies can use their economic power to ruin
        people’s lives. A great example of this is Steven Donziger, an american
        attorney who, in trying to stand up to Chevron for causing harm for over
        30,000 indigenous Ecuadorians over oil drilling, had his life ruined,
        his legal practice permits taken away, and has been sentenced to jail,
        all for standing up to a company that harmed thousands.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}forest.png" alt="trees" />
      <p class="description">
        (Pictured above is one result of Chevron’s oil drilling in Ecuador,
        which is currently causing environmental damage and human harm to
        individuals living there.)
      </p>
    </div>
  </Item>
  <h2>
    These are all things many people know about. This isn’t new information,
    just a review of what most already know. So the question is: What can we do
    about it? Well, let’s talk about solutions
  </h2>
  <Item>
    <div slot="left">
      Carbon Tax
      <p>
        A tax on carbon is a good start to force corporations to produce more
        sustainably. A tax on carbon will help to reduce the rate at which
        carbon is pumped into the atmosphere by corporations, and indirectly
        helps encourage the development of clean energy as companies look at
        ways to reduce waste. Another option, which has been advocated by books
        like The Ministry for the Future, is to create a carbon coin as a
        monetary incentive to corporations to stop producing carbon emissions.
      </p>
    </div>
    <div slot="right" />
  </Item>
  <Item>
    <div slot="left">
      Investing in infrastructure
      <p>
        Investing in infrastructure and clean energy is a step in the right
        direction for fixing the massive problems capitalism faces. Investing in
        our infrastructure could create millions of well paying jobs that
        provide not only for the people working, but for our planet as a whole
        as we move away from fossil fuels.
      </p>
      <p>
        This applies to other industries, too. Investing in more sustainable
        agriculture, and better public transportation systems which can lower
        carbon emissions from vehicles.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}windmill.png" alt="windmill" />
    </div>
  </Item>
  <Item>
    <div slot="left">
      Consumption
      <p>
        It seems simple, and it is. If we want out of this mess, we’re going to
        have to find ways of consuming less. This can mean basic things like
        eating less meat, using less water when showering, and so on. How this
        is done is a point of contention, as any form of tangible change will
        require mandates (which are never popular). But the simple truth is, if
        we want to better our situation, we have to change.
      </p>
    </div>
    <div slot="right" />
  </Item>
  <Item>
    <div slot="left">
      Organize
      <p>
        It should go without saying, but organizing together with other people
        is a great way to spread information and support for a movement. There’s
        tons of ways to go online and find groups that advocate for important
        things like climate and the removal of big money in politics. Getting
        involved is a catalyst for change.
      </p>
    </div>
    <div slot="right">
      <img src="{baseImagePath}protest.png" alt="protest" />
    </div>
  </Item>
  <Item>
    <div slot="left">
      Contacting government officials
      <p>
        At a basic level, government officials work for us. Writing a letter
        renouncing support of a candidate who takes massive donations from
        corporate lobbyists or is an advocate of big money in politics is a good
        starting point. It may seem like a small thing to do, and it is, but if
        no one does it, nothing will change.
      </p>
      <p>
        You can also write to a congressman or other government official about
        your standpoint on something is another small thing you can do. It isn’t
        much, but it can have an impact if enough people do it.
      </p>
      <p>
        To that end, for anyone who wishes to get in contact with a local
        official:
      </p>
      <a href="https://www.house.gov/representatives/find-your-representative"
        >Find Your Representative | house.gov</a
      >
      <br />
      <a href="https://www.senate.gov/senators/senators-contact.htm"
        >U.S. Senate: Contacting U.S. Senators</a
      >
    </div>
    <div slot="right" />
  </Item>
</Writeup>

<style lang="scss">
  @import '../styles/Writing.scss';
</style>
